# Generated by Django 2.2.2 on 2019-06-10 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='decription',
            new_name='description',
        ),
    ]
